### ISSUE TITLE
ArrayBuffer Exception

### ISSUE THREAD

**Issue by aspandaburkut** [hongfaqiu/TIFFImageryProvider#28]
Thanks for the library @hongfaqiu. I have an issue that when i try to upload tiff file, it does not show up and then a few seconds later RangeError: Array buffer allocation failed error is thrown. How can i fix this? 

![image](https://github.com/hongfaqiu/TIFFImageryProvider/assets/161609418/b7c0c8db-fa5b-4d98-955e-9fdb0cf0a0f2)

**Comment by hongfaqiu** [comment]
@aspandaburkut Is the TIFF file you added a native TIFF file, and what is its size? This error may occur because the resolution of the added TIFF image is too high, exceeding the memory that the browser can allocate.
It is suggested to convert it to COGTIFF and then try adding it again.

**Comment by aspandaburkut** [comment]
@hongfaqiu I'm exporting data from SASPlanet as both GeoTIFF and COGTIFF format. My resolution is 264193x102094 for 15 zoom levels and I use ZIP compression of 6 levels and number of tiles is 1033x400 (413200).

**Comment by hongfaqiu** [comment]
@aspandaburkut Could you provide a sample data? I will fix this issue when I have time next week.

**Comment by aspandaburkut** [comment]
@hongfaqiu Here it is sample data. But it is only there for 1 week. [https://we.tl/t-QPjnlFZtHT](url)

**Comment by hongfaqiu** [comment]
> @hongfaqiu Here it is sample data. But it is only there for 1 week. "https://we.tl/t-QPjnlFZtHT"

Copy that!

**Comment by aspandaburkut** [comment]
Hi @hongfaqiu, did you have any time for fixing the issue? I've been through a deep searching phase but I couldn't make any progress. Thank you in advance for your return.

**Comment by aspandaburkut** [comment]
Okey, thank you for interest @hongfaqiu . I'm waiting for your response, have a good day.

**Comment by hongfaqiu** [comment]
> Okey, thank you for interest @hongfaqiu . I'm waiting for your response, have a good day.

@aspandaburkut I'm sorry for the inconvenience. Today has been very busy for me, and I have to postpone once again. Perhaps next week I will have some time. The data you sent me last time is on my work computer, and I am unable to debug it from home.

**Comment by aspandaburkut** [comment]
Thank you, I've sent sample data again. You can redownload when you are free. The link is "https://we.tl/t-ZTkil9Mq7w"

**Comment by hongfaqiu** [comment]
@aspandaburkut 
I opened these two TIFF files in QGIS (which took several minutes), and it turns out they are both raster images. 

![image](https://github.com/hongfaqiu/TIFFImageryProvider/assets/62411296/9ee10791-0738-4eb3-97fb-e09d4f60eb89)
I suggest publishing the results of image registration like these as TMS (Tile Map Service) tiles to achieve the fastest request speed.

If you need to load these two TIFF files on the web, I recommend converting them to COG (Cloud-Optimized GeoTIFF) format and adjusting the tileSize to be below 1024. The error you encountered is likely due to the current low number of levels and the oversized tileSize.

**Comment by aspandaburkut** [comment]
@hongfaqiu Thank you for helping, have a nice day.
